### PR TITLE
Fix draw.aaline not always solid (and wasn't passing unit tests)

### LINKED ISSUE #2120: line drawn with aaline is not always "solid" all the way in pygame 2.dev12
It seems like aaline drawing in pygame 2 works a bit different compared to pygame 1. The below pictures show 3 lines with different angle, but the issue it can happen at other angles as well.

pygame 2.0.0.dev12 (SDL 2.0.12, python 3.8.4) (On windows)
image

pygame 1.9.6
image

Code to reproduce:

```python
import pygame

pygame.init()

screen = pygame.display.set_mode((600, 600))

while True:
    for event in pygame.event.get():
        if (
            event.type == pygame.QUIT
            or event.type == pygame.KEYDOWN
            and (event.key in [pygame.K_ESCAPE, pygame.K_q])
        ):
            exit()

    screen.fill(pygame.Color("black"))

    lines = [
        [(200, 175), (93, 401)],
        [(250, 175), (249, 424)],
        [(300, 175), (333, 422)],
    ]

    for p1, p2 in lines:
        pygame.draw.aaline(screen, pygame.Color("lightgray"), p1, p2)

    pygame.display.flip()

```

### PR DESCRIPTION
**Pull request by siggisv**
- [x] Fix #2120

This should also adress most of #522 :
- [x] Make `draw.aaline()` pass all unit tests that were previously skipped
- [ ] ~~Document expected behavior of `draw.aaline()`~~ (Will do later in a separate PR)

Also:
- [x] Write and run speed tests
- [x] Improve performance if possible/needed.

### CODE REVIEW

**Comment by siggisv** [comment]
Oh! `round()` is a C99 function.

Well that will be easy to fix.

**Comment by siggisv** [comment]
Running this speed test ...
```python
import timeit
import pygame as pg
import random


bground = (255, 255, 255, 0)
color = (0, 128, 0, 0)
lines = []

def drawtest(surface, points):
    for from_p, to_p in points:
        pg.draw.aaline(surface, color, from_p, to_p)

surf = pg.Surface((1920, 1080))
reps = 200

def runtest(line_generator, line_type, line_num = 500):
    random.seed(42) # Use fixed seed to get same set of lines each run
    global lines
    lines = [line_generator() for _ in range(line_num)]
    time_t = min(timeit.repeat("drawtest(surf, lines)",
        setup="from __main__ import drawtest, surf, lines", 
        repeat=reps, number = 1))
    av_single_ms = time_t / line_num * 1000
    print('{} × {} (repeats {}): {:.6f} Av.single: {:.6f}ms'.format(
        line_num, line_type, reps, time_t, av_single_ms))

def small_line():
    x1 = random.uniform(15.0, 1905.0)
    y1 = random.uniform(15.0, 1065.0)
    x2 = x1 + random.uniform(-15.0, 15.0)
    y2 = y1 + random.uniform(-15.0, 15.0)
    return ((x1, y1), (x2, y2))
runtest(small_line, 'small lines', 10000)

def long_line():
    x1 = random.uniform(0.0, 200.0)
    y1 = random.uniform(0.0, 1080.0)
    x2 = random.uniform(1700.0, 1920.0)
    y2 = random.uniform(0.0, 1080.0)
    return ((x1, y1), (x2, y2))
runtest(long_line, 'long lines', 1000)

def huge_line():
    x1 = random.uniform(-100000.0, -99000.0)
    y1 = random.uniform(-100000.0, -99000.0)
    x2 = random.uniform(99000.0, 100000.0) + 1920
    y2 = random.uniform(99000.0, 100000.0) + 1080
    return ((x1, y1), (x2, y2))
runtest(huge_line, 'huge lines', 50)

def small_straight_line():
    x1 = random.uniform(20.0, 1900.0)
    x2 = x1 + random.uniform(-20.0, 20.0)
    y = random.uniform(0.0, 1080.0)
    return ((x1, y), (x2, y))
runtest(small_straight_line, 'small straight lines', 10000)

def long_straight_line():
    x1 = random.uniform(0.0, 200.0)
    x2 = random.uniform(1700.0, 1920.0)
    y = random.uniform(0.0, 1080.0)
    return ((x1, y), (x2, y))
runtest(long_straight_line, 'long straight lines', 1000)

def huge_straight_line():
    x1 = random.uniform(-100000.0, -99000.0)
    x2 = random.uniform(99000.0, 100000.0) + 1920
    y = random.uniform(0.0, 1080.0)
    return ((x1, y), (x2, y))
runtest(huge_straight_line, 'huge straight lines', 50)
```

... gave the following results:

- Commit 6a55a1b:
  - Small lines (random lines within the surface with length in the range 0 to 22px), 
    average time per line ca. 0.0019ms
  - Long lines (random lines within the surface with length in the range 1500 to 2200px), 
    average time per line ca. 0.125ms
  - Huge lines (random lines with both endpoints far outside the surface, length in the range ca. 282,000 to ca 285,000px ), 
    average time per line ca. 3.275ms
  - Small straight lines (random horizontal lines within the surface with length in the range 0 to 20px),
    average time per line ca. 0.0012ms
  - Long straight lines (random horizontal lines within the surface with length in the range 1500 to 1920px),
    average time per line ca. 0.092ms
  - Huge straight lines (random horizontal lines with both endpoints far outside the surface, length in the range 198,000 to 200,000px),
    average time per line ca. 4.15ms
- Commit 439505c:
  - Small lines (random lines within the surface with length in the range 0 to 22px), 
    average time per line ca. 0.0022ms
    _(ca. 15% longer time than 6a55a1b)_
  - Long lines (random lines within the surface with length in the range 1500 to 2200px), 
    average time per line ca. 0.127ms
    _(ca. 1.5% longer time than 6a55a1b)_
  - Huge lines (random lines with both endpoints far outside the surface, length in the range ca. 282,000 to ca 285,000px ), 
    average time per line ca. 2.62ms
    _(ca. 20% **shorter** time than 6a55a1b)_
  - Small straight lines (random horizontal lines within the surface with length in the range 0 to 20px),
    average time per line ca. 0.0012ms
    _(ca. same time)_
  - Long straight lines (random horizontal lines within the surface with length in the range 1500 to 1920px),
    average time per line ca. 0.097ms
    _(ca. 5% longer time than 6a55a1b)_
  - Huge straight lines (random horizontal lines with both endpoints far outside the surface, length in the range 198,000 to 200,000px),
    average time per line ca. 2.55ms
    _(ca. 39% **shorter** time than 6a55a1b)_

**Comment by siggisv** [comment]
The problem (#2120) has been fixed, `aaline` also passes all the unit tests that had been skipped and I've made slight improvisation to it's performance.

I do have some ideas about further improvements to performance but I'll have to skip them for now. IMO this is good enough for now.

File: src_c/draw.c [hunk 1]
```diff
@@ -1161,45 +1161,193 @@ draw_aaline(SDL_Surface *surf, Uint32 color, float from_x, float from_y,
...
     int x, x_pixel_start, x_pixel_end;
     Uint32 pixel_color;
-    int steep = (to_x - from_x < 0 ? - (to_x - from_x) : (to_x - from_x)) <
-                (to_y - from_y < 0 ? - (to_y - from_y) : (to_y - from_y));
+    float x_gap, y_endpoint, clip_left, clip_right, clip_top, clip_bottom;
+    int steep, y;
+
+    dx = to_x - from_x;
+    dy = to_y - from_y;
+
```
Comment (illume) [inline src_c/draw.c:1169]: Great commentary :)

**Comment by illume** [comment]
Does one of the tests that it now passes cover the `line drawn with aaline is not always "solid" all the way` issue in https://github.com/pygame/pygame/issues/2120

**Comment by siggisv** [comment]
> Does one of the tests that it now passes cover the `line drawn with aaline is not always "solid" all the way` issue in #2120

Yes, two of them would have detected that (if they had not already been failing because of other bugs).

**Review by MightyJosip — APPROVED** [review]
Thanks, this pull request looks great. Now the lines look even better than the ones in the older pygame versions before last changes (for example in dev6

And now: 


Lines are just a little bit slower (most I could get was around 23% compared to dev6, but that aalines had another problems (and fixing those in dev8 is the reason why it is a bit slower in newer versions)). I will let illume merge it, but in my opinion it looks great.

Thanks again 👍

**Review by illume — APPROVED** [review]
🎉
