### PR TITLE
Re-order display fullscreen handling and ensure toggle_fullscreen works for maximized window

### LINKED ISSUE #2380: display.toggle_fullscreen does not work when toggling a maximized window to fullscreen
**Environment:**
pygame 2.0.0 (SDL 2.0.12, python 3.7.9)

- **Operating system** windows 7
- **Python version** 3.7.9
- **SDL version** 2.0.12
- **PyGame version** 2.0.0:

**Current behavior:**

When toggling fullscreen from a windowed, maximized window, it tries to do it, fails, gives this warning:
`Warning: re-creating window in toggle_fullscreen` 
then a windowed screen is displayed: that is not re-sizable

**Expected behavior:**

The same as non-maximized windows

**Steps to reproduce:**

Inspect the sample code: set isFullSreen to True if you want to start with a fullscreen (same behaviour)
Toggle fullscreen with F a couple of times: that works just fine. 
then maximize the window, and press F to see the problem arise. 

**Test code**

```
#!/usr/bin/env python3
import os
import pygame

pygame.init()

# find out & store desktopSize
pgdi=pygame.display.Info()
desktopSize=(pgdi.current_w, pgdi.current_h)

FPS = 100
clock = pygame.time.Clock()

screenWidth=160 # initial screen width when windowed
screenHeight=120

hor=0 # ball position on screen 
ver=0

# will make the first intance of the window appear in the middle of the screen.
# (consecutive instances will appear in the upper most left corner)
os.environ['SDL_VIDEO_CENTERED'] = '1' 

# flag to keep track of the question: is the window maximized or not
# should remain False at startup
maximized=False 

# choose to startup fullscreen or not.
# both options will work fine
isFullScreen=True 

# set up initial display:

# always make the non-fullscreen screen first, 
# so the fullscreen has something to toggle back to that is placed properly (as in not at 0,0 )
screen = pygame.display.set_mode((screenWidth,screenHeight), pygame.RESIZABLE) 

if isFullScreen:
    # set size to desktop 
    # not doing this takes much longer (about 4 seconds)
    # but doing this is near instantanious
    pygame.display.set_mode(desktopSize, pygame.RESIZABLE) 
    
    pygame.display.toggle_fullscreen() # now toggle fullscreen


done=False
while not done:
    for event in pygame.event.get():        
        if event.type == pygame.QUIT: 
            # like ctrl-break or the cross in the title bar
            done = True
        elif event.type == pygame.KEYDOWN and event.key == pygame.K_q: 
            # pressing q will also quit the program
            done = True
        elif event.type == pygame.KEYDOWN and event.key == pygame.K_f:
            # pressing f will toggle fullscreen
            
            isFullScreen=not isFullScreen # toggle fullscreen flag
            if isFullScreen: #toggling from not fullscreen to fullscreen
                # store size of windowed screen 
                # so we can reset it when toggling back
                screenWidth=screen.get_width()
                screenHeight=screen.get_height()
            
                # set the number of pixels to desktop size
                pygame.display.set_mode(desktopSize, pygame.RESIZABLE) 
                # then toggle that to fullscreen                
                pygame.display.toggle_fullscreen()                    
                    
            else: # toggling from fullscreen to not fullscreen
                pygame.display.toggle_fullscreen() 
                # restore to old size
                pygame.display.set_mode((screenWidth, screenHeight), pygame.RESIZABLE)
            
    # show some things on screen:        
    # paint background
    screen.fill((255, 0, 255))

    # slide ball position
    hor += 1
    hor = hor % screen.get_width()
    ver += hor % 2
    ver = ver % screen.get_height()
    
    # paint ball
    pygame.draw.circle(screen, (255, 255, 255), (hor, ver), 5)
        
    pygame.display.flip()
    clock.tick(FPS)

```

### LINKED ISSUE #2711: Pygame 2.0.2.dev2 -> NOFRAME and RESIZABLE flags not working when switching from fullscreen back to windowed mode
**Environment:**

- **Operating system** Windows 10
- **Python version** Python 3.9.5
- **SDL version** SDL 2.0.16
- **PyGame version** Pygame 2.0.2.dev2

**Current behavior:**

The NOFRAME and RESIZABLE flags do not work when switching from fullscreen mode back to windowed mode, and a non-resizable 'framed' window is set, but the SCALED flag works fine for all cases. This issue can be overriden when the window is set at least 2 times after reverting from fullscreen mode. 

**Expected behavior:**

When window is switched to windowed mode from fullscreen to windowed mode with the NOFRAME or RESIZABLE flags (or both of them), then the window should have no title bar, and be resizable respectively.

**Screenshots**

Before fullscreen toggle:
image

In fullscreen mode:
image

Switching to windowed mode after fullscreen mode with NOFRAME flag:
image

**Steps to reproduce:**

1. open command prompt or powershell
2. pip install pygame==2.0.2.dev2
3. press any key twice after running the example code

**Test code**

```
import pygame

pygame.init()

fullscreen = False
size = (1280, 720)

full_flags = pygame.FULLSCREEN | pygame.SCALED
normal_flags = pygame.NOFRAME | pygame.RESIZABLE | pygame.SCALED


def toggle_fullscreen(f):
    if f:
        return pygame.display.set_mode(size, full_flags)
    # pygame.display.set_mode(size, normal_flags)  # uncomment this to see issue being fixed as a workaround
    return pygame.display.set_mode(size, normal_flags)


screen = pygame.display.set_mode(size, normal_flags)

clock = pygame.time.Clock()

while True:
    screen.fill("purple")

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            raise SystemExit

        if event.type == pygame.KEYDOWN:
            fullscreen = not fullscreen
            screen = toggle_fullscreen(fullscreen)

    pygame.display.flip()
    clock.tick(144)  # framerate

```

### PR DESCRIPTION
**Pull request by Temmie3754**
This PR resolves #2711 and #3107 by changing the order that changing the fullscreen flag is handled so that it sets the window to be not fullscreen before handling the borderless and resizeable flag as when in fullscreen SDL ignores these changes.
It also partly fixes #2380 as it succeeds at creating a fullscreen window and when exiting retains the resize flag of the window but it still results in a warning message as it has to recreate the window. The toggle function could likely still be improved in this regard but for now this PR fixes the main issues found with it.

### CODE REVIEW

**Review by ankith26 — APPROVED** [review]
Wow, I'm quite impressed!
This seemingly simple fix fixes 3 really complex-looking issues! 🥳 🎉 
I could reproduce all three issues being fixed (the first 2 were spot on, the third `toggle_fullscreen` one was a bit problematic and I came across other minor and unrelated bugs, but the main issue in there is probably fixed)

We have other issues to be tracking `toggle_fullscreen` problems, and this PR does good progress already, thanks a ton! 🍰 🍕 

(due to the nature of what this is fixing, I'd like if we could get more than 3 reviewers, and from my side I'm supporting this PR to quickly make it to the next dev release for wider testing)

File: src_c/display.c [hunk 1]
```diff
@@ -1112,6 +1112,12 @@ pg_set_mode(PyObject *self, PyObject *arg, PyObject *kwds)
                  this invalidates the display surface*/
                 SDL_SetWindowTitle(win, title);
                 SDL_SetWindowSize(win, w_1, h_1);
+                if (0 !=
+                    SDL_SetWindowFullscreen(
+                        win, sdl_flags & (SDL_WINDOW_FULLSCREEN |
+                                          SDL_WINDOW_FULLSCREEN_DESKTOP))) {
+                    return RAISE(pgExc_SDLError, SDL_GetError());
+                }
```
Comment (ankith26) [inline src_c/display.c:1120]: To avoid potential future regressions, a comment above this explaining it has to come before setting other flags like resize/bordered/hidden etc would be nice

**Comment by Temmie3754** [comment]
I've updated it so that it now has the correct formatting and contains a comment for that specified section. I also wrote some further changes for the toggle_fullscreen so that it preserves these flags and the position as well. Also related issue #2698 is fixed by this PR. These changes will require further review to check that no issues are brought about by them.

**Review by ankith26 — COMMENTED** [review]
I think the `fullscreen_backup_x`/`fullscreen_backup_y` stuff are redundant now. Those were added as part of #2460 to workaround a similar issue (and I suspect most of #2460 could now be reverted), because this fix of handling fullscreen first and then doing other display stuff also fixes the issue that PR was fixing

**Comment by Temmie3754** [comment]
Unfortunately the backup positions are still required since those get modified when going into fullscreen as it changes the position to (0, 0) when entering fullscreen. Fullscreen was already handled before position anyway so it isn't affected by this change. This does however implement the same fix #2460 used for toggle_fullscreen now to enable position saving since that was left out when the PR was made.

File: src_c/display.c [hunk 2]
```diff
@@ -2096,7 +2100,7 @@ pg_toggle_fullscreen(PyObject *self, PyObject *_null)
     if (!win)
         return RAISE(pgExc_SDLError, "No open window");
 
-    flags = SDL_GetWindowFlags(win) & SDL_WINDOW_FULLSCREEN_DESKTOP;
+    flags = SDL_GetWindowFlags(win);
     /* SDL_WINDOW_FULLSCREEN_DESKTOP includes SDL_WINDOW_FULLSCREEN */
```
Comment (ankith26) [inline src_c/display.c:2104]: Now that the line above is changed, the comment just below it seems a bit out of place. Should it be moved elsewhere?

File: src_c/display.c [hunk 3]
```diff
@@ -2273,7 +2278,8 @@ pg_toggle_fullscreen(PyObject *self, PyObject *_null)
                              1) != 0) {
                 return NULL;
             }
-            win = SDL_CreateWindow(state->title, wx, wy, w, h, 0);
+            flags &= ~SDL_WINDOW_FULLSCREEN_DESKTOP;
+            win = SDL_CreateWindow(state->title, wx, wy, w, h, flags);
             if (win == NULL) {
                 return RAISE(pgExc_SDLError, SDL_GetError());
             }
```
Comment (ankith26) [inline src_c/display.c:2285]: The comment in this block of code says it's a hack for SDL 2.0.8 (which is a rather old version)... not sure whether it's relevant to this day? Would need someone running pygame on linux with x11 to check though

**Review by MyreMylar — APPROVED** [review]
This fixes the two main linked issues for me, with the slight caveat that one of them also seems to want a resize able window without a frame which isn't a thing in the Windows platform where you resize and move windows by dragging the frame around.

**Comment by Temmie3754** [comment]
Alright fixed that comment so it's now where the flag is actually mentioned, looks like everything has been resolved.

**Review by illume — APPROVED** [review]
Thanks. Works really well.
