### PR TITLE
Fix the SystemError when no type specific clipboard content exists

### LINKED ISSUE #915: SystemError raised when retrieving a data type that has no clipboard content
When a pygame application has ownership of the clipboard, calling `pygame.scrap.get()` to retrieve a data type with no clipboard content causes a `SystemError`.

---

Expected result:
- `None` should be returned (as it is when the pygame application does not have ownership of the clipboard).

Actual result:
- A `SystemError` is raised.

---

Running this code causes a `SystemError`.
```
# Filename: scrap_get_error.py
import pygame

pygame.init()
screen = pygame.display.set_mode((100, 100))
pygame.scrap.init()

print('\nscrap.lost() =', pygame.scrap.lost())
print('clipboard SCRAP_BMP:', pygame.scrap.get(pygame.SCRAP_BMP))

# Acquire the clipboard.
pygame.scrap.put(pygame.SCRAP_TEXT, b'text to clipboard')

print('\nscrap.lost() =', pygame.scrap.lost())
print('clipboard SCRAP_TEXT:', pygame.scrap.get(pygame.SCRAP_TEXT))
print('clipboard SCRAP_BMP:', pygame.scrap.get(pygame.SCRAP_BMP))

pygame.quit()
```

The above code produces this output.
```
pygame 1.9.5.dev0
Hello from the pygame community. https://www.pygame.org/contribute.html

scrap.lost() = True
clipboard SCRAP_BMP: None

scrap.lost() = False
clipboard SCRAP_TEXT: b'text to clipboard'
Traceback (most recent call last):
  File "scrap_get_error.py", line 16, in <module>
    print('clipboard SCRAP_BMP:', pygame.scrap.get(pygame.SCRAP_BMP))
SystemError: <built-in function get> returned NULL without setting an error
```

---

System details:
- os: windows 10 (64bit)
- python: 3.7.2 (64bit) and 2.7.10 (64bit)
- pygame: 1.9.4 and 1.9.5.dev0 (SDL: 1.2.15) at 15b1c1fd97682f5cdcbe6c24d55ab0c829a5c743

### PR DESCRIPTION
**Pull request by charlesej**
This update fixes the `SystemError` that was raised when retrieving a data type that has no clipboard content.

System details:
- os: windows 10 (64bit)
- python: 3.7.2 (64bit) and 2.7.10 (64bit)
- pygame: 1.9.5.dev0 (SDL: 1.2.15) at 3c4af5613285cf10dd36ef20bc0e79e0c898ce4b

Resolves #915.

### CODE REVIEW

File: src_c/scrap.c [hunk 1]
```diff
@@ -222,7 +222,12 @@ _scrap_get_scrap(PyObject *self, PyObject *args)
                 val = PyDict_GetItemString(_clipdata, scrap_type);
```
Comment (dlon) [inline src_c/scrap.c]: Should `PyDict_GetItemWithError()` be used just to be safe?

Comment (charlesej) [reply src_c/scrap.c]: Yes, good idea.
