### PR TITLE
Fix warnings reported by charlesej. Close RWops file handle explicitly using pgRWopsReleaseObject().

### LINKED ISSUE #792: Font files not being closed
In some cases of font creation, the font files are not being closed.

The following code run with the warnings set to default (`python -Wd font_resource_warning.py`), produces unclosed font file `ResourceWarnings`.

Notes:
- There does not appear to be any warnings for some of the `ftfont` calls.
- The output for pygame 1.9.5.dev0 has more warnings than for pygame 1.9.4. The latter only seems to produce warnings when `Font()` is given `None` as the filename.

```
# File font_resource_warning.py.
import pygame
import pygame.freetype
import pygame.ftfont

SPACER = '-' * 75

# Test font.
pygame.font.init()

print(SPACER)
print(r"pygame.font.Font(r'c:\windows\fonts\arial.ttf', 20)""\n")
pygame.font.Font(r'c:\windows\fonts\arial.ttf', 20)

print(SPACER)
print(r"pygame.font.SysFont('arial', 20)""\n")
pygame.font.SysFont('arial', 20)

print(SPACER)
print(r"pygame.font.Font(None, 20)""\n")
pygame.font.Font(None, 20)
pygame.font.quit()


# Test freetype.
pygame.freetype.init()

print(SPACER)
print(r"pygame.freetype.Font(r'c:\windows\fonts\arial.ttf', 20)""\n")
pygame.freetype.Font(r'c:\windows\fonts\arial.ttf', 20)

print(SPACER)
print(r"pygame.freetype.SysFont('arial', 20)""\n")
pygame.freetype.SysFont('arial', 20)

print(SPACER)
print(r"pygame.freetype.Font(None, 20)""\n")
pygame.freetype.Font(None, 20)
pygame.freetype.quit()


# Test ftfont.
pygame.ftfont.init()

print(SPACER)
print(r"pygame.ftfont.Font(r'c:\windows\fonts\arial.ttf', 20)""\n")
pygame.ftfont.Font(r'c:\windows\fonts\arial.ttf', 20)

print(SPACER)
print(r"pygame.ftfont.SysFont('arial', 20)""\n")
pygame.ftfont.SysFont('arial', 20)

print(SPACER)
print(r"pygame.ftfont.Font(None, 20)""\n")
pygame.ftfont.Font(None, 20)
print(SPACER)
pygame.ftfont.quit()
```

Using pygame 1.9.5.dev0 (at 735a0823f71b28f3379d2d01c45cadd05d245e05), the above code gives the following output.
```
pygame 1.9.5.dev0
Hello from the pygame community. https://www.pygame.org/contribute.html
---------------------------------------------------------------------------
pygame.font.Font(r'c:\windows\fonts\arial.ttf', 20)

font_resource_warning.py:12: ResourceWarning: unclosed file <_io.BufferedReader name='c:\\windows\\fonts\\arial.ttf'>
  pygame.font.Font(r'c:\windows\fonts\arial.ttf', 20)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
---------------------------------------------------------------------------
pygame.font.SysFont('arial', 20)

C:\Program Files\Python37\lib\site-packages\pygame-1.9.5.dev0-py3.7-win-amd64.egg\pygame\sysfont.py:285: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\WINDOWS\\Fonts\\arial.ttf'>
  font = pygame.font.Font(fontpath, size)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
---------------------------------------------------------------------------
pygame.font.Font(None, 20)

font_resource_warning.py:20: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\Program Files\\Python37\\lib\\site-packages\\pygame-1.9.5.dev0-py3.7-win-amd64.egg\\pygame\\freesansbold.ttf'>
  pygame.font.Font(None, 20)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
font_resource_warning.py:20: ResourceWarning: unclosed file <_io.BufferedReader name=b'C:\\Program Files\\Python37\\lib\\site-packages\\pygame-1.9.5.dev0-py3.7-win-amd64.egg\\pygame\\freesansbold.ttf'>
  pygame.font.Font(None, 20)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
---------------------------------------------------------------------------
pygame.freetype.Font(r'c:\windows\fonts\arial.ttf', 20)

font_resource_warning.py:29: ResourceWarning: unclosed file <_io.BufferedReader name='c:\\windows\\fonts\\arial.ttf'>
  pygame.freetype.Font(r'c:\windows\fonts\arial.ttf', 20)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
---------------------------------------------------------------------------
pygame.freetype.SysFont('arial', 20)

font_resource_warning.py:33: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\WINDOWS\\Fonts\\arial.ttf'>
  pygame.freetype.SysFont('arial', 20)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
---------------------------------------------------------------------------
pygame.freetype.Font(None, 20)

C:\Program Files\Python37\lib\site-packages\pygame-1.9.5.dev0-py3.7-win-amd64.egg\pygame\freetype.py:60: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\Program Files\\Python37\\lib\\site-packages\\pygame-1.9.5.dev0-py3.7-win-amd64.egg\\pygame\\freesansbold.ttf'>
  super(Font, self).__init__(file, *args, **kwargs)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
---------------------------------------------------------------------------
pygame.ftfont.Font(r'c:\windows\fonts\arial.ttf', 20)

---------------------------------------------------------------------------
pygame.ftfont.SysFont('arial', 20)

---------------------------------------------------------------------------
pygame.ftfont.Font(None, 20)

C:\Program Files\Python37\lib\site-packages\pygame-1.9.5.dev0-py3.7-win-amd64.egg\pygame\ftfont.py:47: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\Program Files\\Python37\\lib\\site-packages\\pygame-1.9.5.dev0-py3.7-win-amd64.egg\\pygame\\freesansbold.ttf'>
  super(Font, self).__init__(file, size=size, resolution=resolution)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
---------------------------------------------------------------------------
```

Using pygame 1.9.4, the above code gives the following output.
```
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
---------------------------------------------------------------------------
pygame.font.Font(r'c:\windows\fonts\arial.ttf', 20)

---------------------------------------------------------------------------
pygame.font.SysFont('arial', 20)

---------------------------------------------------------------------------
pygame.font.Font(None, 20)

font_resource_warning.py:20: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\Program Files\\Python37\\lib\\site-packages\\pygame\\freesansbold.ttf'>
  pygame.font.Font(None, 20)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
---------------------------------------------------------------------------
pygame.freetype.Font(r'c:\windows\fonts\arial.ttf', 20)

---------------------------------------------------------------------------
pygame.freetype.SysFont('arial', 20)

---------------------------------------------------------------------------
pygame.freetype.Font(None, 20)

C:\Program Files\Python37\lib\site-packages\pygame\freetype.py:60: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\Program Files\\Python37\\lib\\site-packages\\pygame\\freesansbold.ttf'>
  super(Font, self).__init__(file, *args, **kwargs)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
---------------------------------------------------------------------------
pygame.ftfont.Font(r'c:\windows\fonts\arial.ttf', 20)

---------------------------------------------------------------------------
pygame.ftfont.SysFont('arial', 20)

---------------------------------------------------------------------------
pygame.ftfont.Font(None, 20)

C:\Program Files\Python37\lib\site-packages\pygame\ftfont.py:45: ResourceWarning: unclosed file <_io.BufferedReader name='C:\\Program Files\\Python37\\lib\\site-packages\\pygame\\freesansbold.ttf'>
  super(Font, self).__init__(file, size=size, resolution=resolution)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
---------------------------------------------------------------------------
```

Each of the above font calls can be tested in isolation to see its particular warning. Here's some example code for testing just one font object creation.

```
# File font_resource_warning_solo.py.
import pygame
pygame.font.init()
pygame.font.Font(r'c:\windows\fonts\arial.ttf', 20)
pygame.font.quit()
```

The above code gives the following output.
```
pygame 1.9.5.dev0
Hello from the pygame community. https://www.pygame.org/contribute.html
font_resource_warning_solo.py:3: ResourceWarning: unclosed file <_io.BufferedReader name='c:\\windows\\fonts\\arial.ttf'>
  pygame.font.Font(r'c:\windows\fonts\arial.ttf', 20)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

System details:
- os: windows 10 (64bit)
- python: 3.7.2 (64bit)
- pygame: 1.9.5.dev0 (SDL: 1.2.15) at 735a0823f71b28f3379d2d01c45cadd05d245e05

### PR DESCRIPTION
**Pull request by dlon**
See #792. Prevent "unclosed file" warning by explicitly closing a file handle when loading fonts.

Close #792.

### CODE REVIEW

**Comment by dlon** [comment]
I was able to fix the remaining warnings.

Close #792.

File: src_c/rwobject.c [hunk 1]
```diff
@@ -437,21 +437,10 @@ pgRWopsFromFileObject(PyObject *obj)
...
-        PyMem_Del(helper);
-        SDL_FreeRW(context);
-    } else {
-        int ret;
-        if ((ret = SDL_RWclose(context)) < 0) {
-            RAISE(PyExc_IOError, SDL_GetError());
-            return ret;
-        }
+    int ret;
+    if ((ret = SDL_RWclose(context)) < 0) {
```
Comment (charlesej) [inline src_c/rwobject.c]: Forcing the font file closed will make it unusable for others that are relying on it being open. It is probably best to just close the file where it has been opened. With this change the following code will just show a blank screen.

```
import time
import pygame
import pygame.freetype

pygame.init()

screen = pygame.display.set_mode((200, 100))
font_file_obj = open(r'c:\windows\fonts\arial.ttf', 'rb')

ft1 = pygame.freetype.Font(font_file_obj, 20)
ft2 = pygame.freetype.Font(font_file_obj, 40)
del ft1
ft2_text, _ = ft2.render('test font', pygame.Color('white'),
                         pygame.Color('blue'))

screen.blit(ft2_text, (0, 0))
pygame.display.flip()
time.sleep(2)

pygame.quit()
```

**Comment by charlesej** [comment]
I've submitted PR #796 which should clear up closing any remaining files that are not handled by your changes to `_freetype.c` and `font.c`.

File: src_c/rwobject.c (hunk 1 above)
Comment (dlon) [reply src_c/rwobject.c]: Agreed. I'll make it close the file only if the refcount is 1. Then it should only warn if the user fails to close the handle. If pygame has the only reference to the handle, then it should be safe to close.
