### PR TITLE
Added border_radius keyword for draw.rect and drawing of one circle quadrant, fixed bounding rects

### LINKED ISSUE #895: Incorrect bounding rects returned from pygame.draw.line/aaline
The bounding rects returned from `pygame.draw.line` and `pygame.draw.aaline` are incorrect in some instances.

The related [pygame.draw documentation](https://www.pygame.org/docs/ref/draw.html) states (with the assumption that 'bounding area' means 'minimum bounding rectangle'):
> The functions return a rectangle representing the bounding area of changed pixels.

Below are a few examples of some issues with the returned bounding rects.

---

The following code draws a line (white) and its returned bounding rect (red).
```
import pygame
import time

pygame.init()
screen = pygame.display.set_mode((320, 320))

rect = pygame.draw.line(screen, pygame.Color('white'), (-1, -1), (320, 320), 1)
pygame.draw.rect(screen, pygame.Color('red'), rect, 1)
print(rect)

pygame.display.flip()
time.sleep(2)
pygame.quit()
```

The above code gives the following output. The returned bounding rect is outside of the screen's bounds. It should consist of coordinates that can be drawn on the screen.
```
pygame 1.9.5.dev0
Hello from the pygame community. https://www.pygame.org/contribute.html
<rect(-1, -1, 322, 322)>
```

draw_line_bounding_rect

---

The following code draws a thick line (white) and its returned bounding rect (red).
```
import pygame
import time

pygame.init()
screen = pygame.display.set_mode((320, 320))

rect = pygame.draw.line(screen, pygame.Color('white'), (60, 240), (240, 60), 30)
pygame.draw.rect(screen, pygame.Color('red'), rect, 1)
print(rect)

pygame.display.flip()
time.sleep(2)
pygame.quit()
```

The above code gives the following output. The returned bounding rect is incorrect. It should be just big enough to fully enclose the line with no parts of the line outside of it.
```
pygame 1.9.5.dev0
Hello from the pygame community. https://www.pygame.org/contribute.html
<rect(60, 60, 210, 181)>
```

draw_thickline_bounding_rect

---

The following code draws an aaline (white) and its returned bounding rect (red).
```
import pygame
import time

pygame.init()
screen = pygame.display.set_mode((320, 320))

rect = pygame.draw.aaline(screen, pygame.Color('white'), (-1, -1), (320, 320))
pygame.draw.rect(screen, pygame.Color('red'), rect, 1)
print(rect)

pygame.display.flip()
time.sleep(2)
pygame.quit()
```

The above code gives the following output. Part of the returned bounding rect is outside of the screen's bounds. It should consist of coordinates that can be drawn on the screen.
```
pygame 1.9.5.dev0
Hello from the pygame community. https://www.pygame.org/contribute.html
<rect(0, 0, 321, 321)>
```

draw_aaline_bounding_rect

---

System details:
- os: windows 10 (64bit)
- python: 3.7.2 (64bit)
- pygame: 1.9.5.dev0 (SDL: 1.2.15) at 811eaf051e86a4c711d42a0d426dfc138668f384

### LINKED ISSUE #1120: How do pygame draw RoundRect?
I want to draw a rectangle with radians，could you help me?

### PR DESCRIPTION
**Pull request by MightyJosip**
This should fix #895, #1120, #1122, #1153, #1212, #1241, #1305 and #1306

### CODE REVIEW

**Comment by illume** [comment]
Thanks @MightyJosip :)

File: src_c/doc/draw_doc.h [hunk 1]
```diff
@@ -20,7 +20,7 @@ pygame module for drawing shapes
 
 pygame.draw.rect
  rect(surface, color, rect) -> Rect
- rect(surface, color, rect, width=0) -> Rect
+ rect(surface, color, rect, width=0, border-radius=0) -> Rect
```
Comment (charlesej) [inline src_c/doc/draw_doc.h]: I think you want `border_radius` here.

File: test/draw_test.py [hunk 2]
```diff
@@ -5141,7 +5141,6 @@ def test_circle__floats(self):
     #     l, t, MAX(r - l, 0), MAX(b - t, 0)
 
     # This decorator can be removed when issue #1122 is resolved.
```
Comment (charlesej) [inline test/draw_test.py]: You can also remove this comment.

**Comment by MightyJosip** [comment]
@charlesej since you did draw documentation, can you just check if I wrote it right, this is my first time I was writing docs and using rst files

File: docs/reST/ref/draw.rst [hunk 3]
```diff
@@ -163,6 +166,9 @@ object around the draw calls (see :func:`pygame.Surface.lock` and
          .. note::
             When using ``width`` values ``> 1``, the edge lines will only grow
             inward.
+   :param int quadrant: (optional) used for drawing only one quadrant of the circle
+      Has to be in the interval [0, 4]. If ``quadrant == 0`` entire circle will be 
+      drawn
```
[the remark this answers is not in the document]
Comment (illume) [reply docs/reST/ref/draw.rst]: Is 0-4 confusing here? I'm not sure if it's better than 0-3, and a default None for quadrant.

If kwargs were used (top_left, top_right, bottom_left, bottom_right) each defaulting to True, then it would make it possible from the API that different quadrants could be True and drawn at once. I'm not sure if that's desirable?

**Comment by illume** [comment]
About quadrant=0-4... Is it confusing? I'm not sure if it's better than 0-3, and a default None for quadrant?

If kwargs were used (top_left, top_right, bottom_left, bottom_right) each defaulting to True, then it would make it possible from the API that different quadrants could be True and drawn at once. I'm not sure if that's desirable?

**Comment by illume** [comment]
@MightyJosip here's an example of usage you asked for.

```python
    pygame.draw.circle(screen, BLUE, [250, 250], 40, 0, top_left=True)
    pygame.draw.circle(screen, RED, [250, 250], 40, 30, 2, top_right=True)
    pygame.draw.circle(screen, GREEN, [250, 250], 40, 20, bottom_right=True)
    pygame.draw.circle(screen, BLACK, [250, 250], 40, 10, bottom_left=True)

    # draw top left, bottom left slices of the circle.
    pygame.draw.circle(screen, BLACK, [250, 250], 40, 10, bottom_left=True, top_left=True)
```

They should probably default to None, so that it is not required to call each one with False?
top_left=None, top_right=None, bottom_left=None, bottom_right=None

The only problem is that it doesn't read very well.
- `draw_top_left=True`
- `quad_tl=True`
- `quad_top_left=True`
- ...

**Comment by illume** [comment]
Regarding: 
> it should be pretty trivial for me to make all corners different

Do you mean for the rounded corners?

In css they do let each corner be controlled with separate rules:
> border-top-left-radius: 1px
> border-top-right-radius: 2px
> border-bottom-left-radius: 3px
> border-bottom-right-radius: 4px

This way they have the default border-radius, and then each other rule can override that.
So it's possible to do (all corners 5px except top left at 10px):
> border-radius: 5px
> border-top-left-radius: 10px

**Comment by illume** [comment]
I updated the example usage comment above with the quadrant=, and top_left= styles to make comparison easier.

**Comment by MightyJosip** [comment]
With latest commit #1241, #1212, #1305, #1306, #1153 and #895 should also be fixed

File: src_c/draw.c [hunk 4]
```diff
@@ -1564,114 +1694,216 @@ draw_arc(SDL_Surface *dst, int x, int y, int radius1, int radius2,
...
+            if ((y0 - y1) <= (y0 - x))
+                set_at(dst, x0 - x, y0 - y1, color, drawn_area);          /* 3 */
+            if ((x0 + y1 - 1) >= (x0 + x - 1))
+                set_at(dst, x0 + y1 - 1, y0 + x - 1, color, drawn_area);  /* 8 */
+            if ((x0 - y1) <= (x0 - x))
+                set_at(dst, x0 - y1, y0 + x - 1, color, drawn_area);      /* 5 */
+            if ((x0 + y1 - 1) >= (x0 + x - 1))
+                set_at(dst, x0 + y1 - 1, y0 - x, color, drawn_area);      /* 1 */
+            if ((x0 - y1) <= (x0 - x))
+                set_at(dst, x0 - y1, y0 - x, color, drawn_area);          /* 4 */
```
Comment (charlesej) [inline src_c/draw.c]: Some of these `if` checks are the same. Can they be combined?

Comment (illume) [reply src_c/draw.c]: Good find. JoKing ran out of time. I'm starting another branch to do this.
