### PR TITLE
clean modinit code, fix bugs, use recommended API

### LINKED ISSUE #2951: Clean up some module initialization code
Port our uses of `PyModule_GetDict` and `PyDict_SetItemString` at the end of the modules to `PyModule_AddObject`.

Mixer, event, surface, rect, all use the older style, certainly more do as well. Font looks like it does it correctly, for an example of good behavior.

Additionally, we could investigate using macros to "port" new python C api functions introduced in 3.9 and 3.10 that could have further convenience for the code. PyModule_AddObjectRef and PyModule_AddType, from this page: https://docs.python.org/3/c-api/module.html.

### PR DESCRIPTION
**Pull request by ankith26**
PR to close #2951

Does some code cleanups around modinit code, fixing a few bugs in the process, and migrating away from `PyModule_GetDict` which is discouraged by the [docs](https://docs.python.org/3/c-api/module.html#c.PyModule_GetDict)

I originally planned to make use of newer API like `PyModule_AddObjectRef` (new in py3.10) and `PyModule_AddType` (new in py3.9) because that makes the modinit code even more elegant, but to do this we'd have to put some hacks on `pyver < 3.10` and I figured this could create problems if we ever intend to use `Py_LIMITED_API`, so I left this for now (but we can still do this when the minimum supported python version is 3.10, and this would happen in 5-6ish years)

### CODE REVIEW

File: src_c/_freetype.c [hunk 1]
```diff
@@ -2205,10 +2205,10 @@ MODINIT_DEFINE(_freetype)
     FREETYPE_MOD_STATE(module)->cache_size = 0;
     FREETYPE_MOD_STATE(module)->resolution = PGFT_DEFAULT_RESOLUTION;
 
-    Py_INCREF((PyObject *)&pgFont_Type);
+    Py_INCREF(&pgFont_Type);
     if (PyModule_AddObject(module, FONT_TYPE_NAME, (PyObject *)&pgFont_Type) ==
         -1) {
```
Comment (Starbuck5) [inline src_c/_freetype.c:2210]: This should just test the value directly, rather than comparing to `-1`, to be consistent with the other ones. Especially since `-1` on failure is not documented.

Comment (ankith26) [reply src_c/_freetype.c:2210]: oh, nice catch! :) I made this change in many other places but forgot to do it here

**Comment by Starbuck5** [comment]
Looking at this code, it looks like there should be a function in base that encapsulates the c api for a module into an object, and adds that object to the module.

It looks like a lot of this takes out error handling for the return of encapsulate_api macro. Which goes into PyCapsule_New, which has error reporting stuff. https://docs.python.org/3/c-api/capsule.html#c.PyCapsule_New

**Comment by ankith26** [comment]
> Looking at this code, it looks like there should be a function in base that encapsulates the c api for a module into an object, and adds that object to the module.

hmmm, yeah maybe that could be done here

> It looks like a lot of this takes out error handling for the return of encapsulate_api macro. 

Yeah that's an intentional change. I only removed that bit because `PyModule_AddObject` simply returns `NULL` when `obj` is `NULL`, so I unified the error handling of `encapsulate_api` and `PyModule_AddObject` to get rid of some code repetition

**Comment by ankith26** [comment]
Ok, that did not go so well, there were issues with that approach, a function cannot be used because `encapsulate_api` is a macro and uses macro string stuff, and there seem to be no elegant ways to make the entire block of code a macro, because that would make error handling more painful, so I guess I'll leave that for now, maybe we can figure something in future PRs ;)

**Comment by Starbuck5** [comment]
> I only removed that bit because PyModule_AddObject simply returns NULL when obj is NULL, so I unified the error handling of encapsulate_api and PyModule_AddObject to get rid of some code repetition

Ah, smart.

File: src_c/_freetype.c [hunk 2]
```diff
@@ -2205,10 +2205,9 @@ MODINIT_DEFINE(_freetype)
     FREETYPE_MOD_STATE(module)->cache_size = 0;
     FREETYPE_MOD_STATE(module)->resolution = PGFT_DEFAULT_RESOLUTION;
 
-    Py_INCREF((PyObject *)&pgFont_Type);
-    if (PyModule_AddObject(module, FONT_TYPE_NAME, (PyObject *)&pgFont_Type) ==
-        -1) {
-        Py_DECREF((PyObject *)&pgFont_Type);
+    Py_INCREF(&pgFont_Type);
```
Comment (Starbuck5) [inline src_c/_freetype.c:2208]: `(PyObject *)`?

File: src_c/base.c [hunk 3]
```diff
@@ -2173,62 +2153,45 @@ MODINIT_DEFINE(base)
...
 #ifdef MS_WIN32
-        SDL_RegisterApp("pygame", 0, GetModuleHandle(NULL));
-#endif
-#if defined(macintosh)
-#if (!defined(__MWERKS__) && !TARGET_API_MAC_CARBON)
-        SDL_InitQuickDraw(&pg_qd);
-#endif
+    SDL_RegisterApp("pygame", 0, GetModuleHandle(NULL));
+#elif defined(macintosh) && !defined(__MWERKS__) && !TARGET_API_MAC_CARBON
+    SDL_InitQuickDraw(&pg_qd);
```
Comment (Starbuck5) [inline src_c/base.c:2188]: QuickDraw is obsolete, so this can be removed.

File: src_c/joystick.c [hunk 4]
```diff
@@ -671,16 +670,20 @@ MODINIT_DEFINE(joystick)
     }
     joy_instance_map = PyObject_GetAttrString(module, "_joy_instance_map");
     Py_DECREF(module);
```
Comment (Starbuck5) [inline src_c/joystick.c:672]: This is kinda strange, do you understand why it is there? I don't.

File: src_c/_freetype.c (hunk 2 above)
Comment (ankith26) [reply src_c/_freetype.c:2208]: Yes this is intentional. Because the incref/decref API are macros, they cast the argument to `(PyObject *)` already, so doing it before the macro call is redundant

File: src_c/base.c (hunk 3 above)
Comment (ankith26) [reply src_c/base.c:2188]: aight, good idea

File: src_c/joystick.c (hunk 4 above)
Comment (ankith26) [reply src_c/joystick.c:672]: It's for joystick events to have the old style ID attribute, IIRC (which is deprecated now)

Comment (Starbuck5) [reply src_c/joystick.c:672]: I mean the `Py_DECREF(module)`

(I thought Github would highlight my selection)

Comment (ankith26) [reply src_c/joystick.c:672]: A few lines above `module = PyImport_ImportModule("pygame.event");` returned a new reference to `module`, and after we have extracted the dict attribute from the event module, we have to decref it.

Perhaps you got confused thinking the joystick module object is being freed, which is not

**Review by Starbuck5 — APPROVED** [review]
Alrighty. Thanks Ankith!

I've read through the whole thing and it looks good.

I also ran the test suite locally and it's still good there.

File: src_c/base.c [hunk 5]
```diff
@@ -2086,59 +2084,41 @@ MODINIT_DEFINE(base)
                                          NULL,
                                          NULL};
 
-    if (!is_loaded) {
```
Comment (illume) [inline src_c/base.c:2089]: Why was the !is_loaded guard removed?

**Review by illume — APPROVED** [review]
Looks ok to me.

I didn't go through each call in detail, didn't look for new warnings, and didn't test locally.

File: src_c/base.c (hunk 5 above)
Comment (ankith26) [reply src_c/base.c:2089]: Because that was a local variable, lol, and was always set to 0 when the init function is called. So the conditional was useless because it will get executed in all cases.
